apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: dy1plsfpm-go 
  janus-idp.io/tekton: dy1plsfpm-go
  backstage.io/kubernetes-id: dy1plsfpm-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: dy1plsfpm-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml