apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: dy1plsfpm-go-gitops
  description: This is GitOps manifest for dy1plsfpm-go   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-selector: rhtap/gitops=dy1plsfpm-go
    backstage.io/kubernetes-id: dy1plsfpm-go 
    backstage.io/techdocs-ref: dir:. 
    janus-idp.io/tekton: dy1plsfpm-go
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:dy1plsfpm-go
